name: menuguru

services:    
  mysql_db:
    build:
      context: ./mysql    
    volumes:
      - db_data:/var/lib/mysql      
    restart: always
    ports:
      - 3306:3306               
    env_file: .env
    healthcheck:    
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 20      
  api_service:
    build:
      context: .         
    restart: on-failure
    ports:
      - 8080:8080
    env_file: .env          
    depends_on:
      mysql_db:
        condition: service_healthy
volumes:
    db_data:        