spring:
  application:
    name: file-processor
  profiles:
    default: docker
  jackson:
    deserialization:
      fail-on-unknown-properties: true     
server:
  servlet:
    context-path: "/file-processor/v1"
---
spring:
  config:
    activate:
      on-profile:
      - docker		
  request:
    serviceUrl: ${REQUEST_SERVICE_URL}
  aws:
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
    sessionToken: ${AWS_SESSION_TOKEN}
    region: ${AWS_REGION}
    s3UploadBucket: ${AWS_S3_UPLOAD_BUCKET}
    s3DownloadBucket: ${AWS_S3_DOWNLOAD_BUCKET}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    ssl:
      enabled: ${RABBITMQ_SSL}