#Caso esteja executando com o Autoscaling desabilitado, especifique o número de replicas
replicaCount: 1

image:
  tag: "latest"

service:
  #Para executar de forma local, altere o "type" para "NodePort"
  type: LoadBalancer
  port: 8080
  cloud: aws

autoscaling:
  #Para habilitar o autoscaling, altere a variavel "enable" para "true" ("replicaCount" será ignorado)
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  
#Configurações da instância MySQL
mysqlUrl: {{ .Env.MYSQL_URL }}
mysqlPort: {{ .Env.MYSQL_PORT }}
mysql_user: {{ .Env.MYSQL_USER }}
mysql_password: {{ .Env.MYSQL_PASSWORD }}

#Configurações do provedor de pagamentos (Mercado Pago)
payment_userId: {{ .Env.{PAYMENT_USER_ID }}
payment_accessToken: {{ .Env.{PAYMENT_ACCESS_TOKEN }}
payment_hostWebhook: {{ .Env.PAYMENT_WEBHOOK }}