name: pipeline
run-name: ${{ github.actor }} is running a new build.

on: [push]

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file 
      
      - run: mvn test

      - name: Genarate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2

      - name: Log coverage percentage
        run: |
            echo "Coverage = ${{ steps.jacoco.outputs.coverage }}"
            echo "Branch coverage = ${{ steps.jacoco.outputs.branches }}"
            
  Build:
    needs: [Unit-Tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file 
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  Quality:
    needs: [Build]
    if: startsWith(github.ref_name, 'master')
        || startsWith(github.ref_name, 'release/')
    runs-on: ubuntu-latest    
    steps:
      - run: echo "Quality"

  Publish:
    if: startsWith(github.ref_name, 'master')
    needs: [Quality]    
    runs-on: ubuntu-latest
    steps:
      - run: echo "Publish"
      
  Deploy:
    if: startsWith(github.ref_name, 'master')
    needs: [Publish]    
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy"      
