name: pipeline
run-name: ${{ github.actor }} is running a new build.

on: [push]

jobs:
  Unit-Tests:
    if: startsWith(github.ref_name, 'master')
        || startsWith(github.ref_name, 'release/')  
        || startsWith(github.ref_name, 'develop')
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file 
      
      - run: mvn test

      - name: Genarate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2

      - name: Log coverage percentage
        run: |
            echo "Coverage = ${{ steps.jacoco.outputs.coverage }}"
            echo "Branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/
            
  Build:
    needs: Unit-Tests
    if: startsWith(github.ref_name, 'master')
        || startsWith(github.ref_name, 'release/')  
        || startsWith(github.ref_name, 'develop')    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file 
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  Publish:
    needs: Build
    if: startsWith(github.ref_name, 'master')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Publish"

  Deploy-STG:
    if: startsWith(github.ref_name, 'develop')
    needs: Publish
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy Stage"

  Smoke-Tests-STG:
    if: startsWith(github.ref_name, 'develop')
    needs: Deploy-STG
    runs-on: ubuntu-latest
    steps:
      - run: echo "Smoke Test"  

  Integration-Tests:
    if: startsWith(github.ref_name, 'develop')
    needs: Smoke-Tests-STG
    runs-on: ubuntu-latest
    steps:
      - run: echo "Integration Test"  

  Deploy-PRE:
    if: startsWith(github.ref_name, 'release/')
    needs: Publish    
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy Pre-Production"     

  Smoke-Tests-PRE:
    if: startsWith(github.ref_name, 'develop')
    needs: Deploy-PRE
    runs-on: ubuntu-latest
    steps:
      - run: echo "Smoke Test"  

  Functional-Tests:
    if: startsWith(github.ref_name, 'develop')
    needs: Smoke-Tests-PRE
    runs-on: ubuntu-latest
    steps:
      - run: echo "Functional Tests"

  Deploy-PRD:
    if: startsWith(github.ref_name, 'master')
    needs: Publish
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy Production"      
