name: pipeline
run-name: ${{ github.actor }} is running a new build.

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file 
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  Tests:
    needs: [Build]
    runs-on: ubuntu-latest    
    steps:
      - run: echo "Testes"

  Quality:
    needs: [Build]
    runs-on: ubuntu-latest    
    steps:
      - run: echo "Quality"

  Publish:
    if: startsWith(github.ref_name, 'master')
    needs: [Tests, Quality]    
    runs-on: ubuntu-latest
    steps:
      - run: echo "Publish"
      
  Deploy:
    if: startsWith(github.ref_name, 'master')
    needs: [Publish]    
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy"      
